### ISSUE TITLE
Exception caught during observer callback: TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by caraya** [Juicy/juicy-markdown#4]
I'm not 100% sure this is an issue with marked so I'll start here

I get the following exception when using Marked in a web component. The result displays so I don't think it's a Marked error. May this be related to why the page is not updating when I make css changes after the first load?

This is how I'm using Juicy Markdown

 ```
 <juicy-markdown value="{{doc}}"   ghcss="false"></juicy-markdown>   
```

This is the exception I get in Chrome 39. 

```
 Exception caught during observer callback: TypeError: Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (http://localhost:8888/athena-document/bower_components/marked/lib/marked.js:137:5)
    at Function.Lexer.lex (http://localhost:8888/athena-document/bower_components/marked/lib/marked.js:128:16)
    at marked (http://localhost:8888/athena-document/bower_components/marked/lib/marked.js:1201:31)
    at juicy-markdown.Polymer.parseText (http://localhost:8888/athena-document/bower_components/juicy-markdown/juicy-markdown.html:72:53)
    at juicy-markdown.Polymer.valueChanged (http://localhost:8888/athena-document/bower_components/juicy-markdown/juicy-markdown.html:68:10)
    at juicy-markdown.properties.invokeMethod (http://localhost:8888/athena-document/bower_components/polymer/polymer.js:9355:12)
    at juicy-markdown.properties.notifyPropertyChanges (http://localhost:8888/athena-document/bower_components/polymer/polymer.js:9344:20)
    at Object.Observer.report_ (http://localhost:8888/athena-document/bower_components/polymer/polymer.js:4890:24)
    at Object.createObject.check_ (http://localhost:8888/athena-document/bower_components/polymer/polymer.js:5296:12)
    at callback (http://localhost:8888/athena-document/bower_components/polymer/polymer.js:4788:20)polymer.js:4893 Observer.report_polymer.js:5296 createObject.check_polymer.js:4788 callback
```

**Comment by internalfx** [comment]
Got same error from marked. But I'm not using juicy.

**Comment by internalfx** [comment]
Got it, because of async loading. marked was getting null passed in.
